[Icon Theme]
Name=Luna
Comment=Windows XP icon pack

Example=folder

# Directory list
Directories=16x16/actions,16x16/apps,16x16/categories,16x16/devices,16x16/mimetypes,16x16/places,16x16/status,16x16/preferences,32x32/actions,32x32/apps,32x32/categories,32x32/devices,32x32/mimetypes,32x32/notifications,32x32/status,32x32/preferences,48x48/actions,48x48/apps,48x48/categories,48x48/devices,48x48/emblems,48x48/mimetypes,48x48/notifications,48x48/places,48x48/status,48x48/preferences,128x128/actions,128x128/emblems,128x128/notifications,128x128/places,128x128/status,128x128/preferences,256x256/actions,256x256/emblems,256x256/notifications,256x256/places,256x256/status,256x256/devices,256x256/preferences,256x256/mimetypes,256x256/categories,256x256/apps

[16x16/actions]
Context=Actions
Size=16
Type=Fixed

[16x16/apps]
Context=Applications
Size=16
Type=Fixed

[16x16/categories]
Context=Categories
Size=16
Type=Fixed

[16x16/devices]
Context=Devices
Size=16
Type=Fixed

[16x16/mimetypes]
Context=MimeTypes
Size=16
Type=Fixed

[16x16/places]
Context=Places
Size=16
Type=Fixed

[16x16/status]
Context=Status
Size=16
Type=Fixed

[16x16/preferences]
Context=Applications
Size=16
Type=Fixed

[32x32/actions]
Context=Actions
Size=32
Type=Fixed

[32x32/apps]
Context=Applications
Size=32
Type=Fixed

[32x32/categories]
Context=Categories
Size=32
Type=Fixed

[32x32/devices]
Context=Devices
Size=32
Type=Fixed

[32x32/mimetypes]
Context=MimeTypes
Size=32
Type=Fixed

[32x32/notifications]
Context=Notifications
Size=32
Type=Fixed

[32x32/status]
Context=Status
Size=32
Type=Fixed

[32x32/preferences]
Context=Applications
Size=32
Type=Fixed

[48x48/actions]
Context=Actions
Size=48
Type=Fixed

[48x48/apps]
Context=Applications
Size=48
Type=Fixed

[48x48/categories]
Context=Categories
Size=48
Type=Fixed

[48x48/devices]
Context=Devices
Size=48
Type=Fixed

[48x48/emblems]
Context=Emblems
Size=48
Type=Fixed

[48x48/mimetypes]
Context=MimeTypes
Size=48
Type=Fixed

[48x48/notifications]
Context=Notifications
Size=48
Type=Fixed

[48x48/places]
Context=Places
Size=48
Type=Fixed

[48x48/status]
Context=Status
Size=48
Type=Fixed

[48x48/preferences]
Context=Applications
Size=48
Type=Fixed

[128x128/actions]
Context=Actions
Size=128
Type=Fixed

[128x128/emblems]
Context=Emblems
Size=128
Type=Fixed

[128x128/notifications]
Context=Notifications
Size=128
Type=Fixed

[128x128/places]
Context=Places
Size=128
Type=Fixed

[128x128/status]
Context=Status
Size=128
Type=Fixed

[128x128/preferences]
Context=Actions
Size=128
Type=Fixed

[256x256/actions]
Context=Actions
Size=256
MinSize=22
MaxSize=512
Type=Scalable

[256x256/apps]
Context=Applications
Size=256
MinSize=22
MaxSize=512
Type=Scalable

[256x256/emblems]
Context=Emblems
Size=256
MinSize=22
MaxSize=512
Type=Scalable

[256x256/notifications]
Context=Notifications
Size=256
MinSize=22
MaxSize=512
Type=Scalable

[256x256/places]
Context=Places
Size=256
MinSize=22
MaxSize=512
Type=Scalable

[256x256/status]
Context=Status
Size=256
MinSize=22
MaxSize=512
Type=Scalable

[256x256/devices]
Context=Devices
Size=256
MinSize=22
MaxSize=512
Type=Scalable

[256x256/preferences]
Context=Actions
Size=256
MinSize=22
MaxSize=512
Type=Scalable

[256x256/mimetypes]
Context=MimeTypes
Size=256
MinSize=22
MaxSize=512
Type=Scalable

[256x256/categories]
Context=Categories
Size=256
MinSize=22
MaxSize=512
Type=Scalable
